/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libjpegturbo_turbojpeg_TJ */

#ifndef _Included_org_libjpegturbo_turbojpeg_TJ
#define _Included_org_libjpegturbo_turbojpeg_TJ
#ifdef __cplusplus
extern "C" {
#endif
#undef org_libjpegturbo_turbojpeg_TJ_NUMSAMPOPT
#define org_libjpegturbo_turbojpeg_TJ_NUMSAMPOPT 4L
#undef org_libjpegturbo_turbojpeg_TJ_SAMP_444
#define org_libjpegturbo_turbojpeg_TJ_SAMP_444 0L
#undef org_libjpegturbo_turbojpeg_TJ_SAMP_422
#define org_libjpegturbo_turbojpeg_TJ_SAMP_422 1L
#undef org_libjpegturbo_turbojpeg_TJ_SAMP_420
#define org_libjpegturbo_turbojpeg_TJ_SAMP_420 2L
#undef org_libjpegturbo_turbojpeg_TJ_SAMP_GRAY
#define org_libjpegturbo_turbojpeg_TJ_SAMP_GRAY 3L
#undef org_libjpegturbo_turbojpeg_TJ_NUMPFOPT
#define org_libjpegturbo_turbojpeg_TJ_NUMPFOPT 7L
#undef org_libjpegturbo_turbojpeg_TJ_PF_RGB
#define org_libjpegturbo_turbojpeg_TJ_PF_RGB 0L
#undef org_libjpegturbo_turbojpeg_TJ_PF_BGR
#define org_libjpegturbo_turbojpeg_TJ_PF_BGR 1L
#undef org_libjpegturbo_turbojpeg_TJ_PF_RGBX
#define org_libjpegturbo_turbojpeg_TJ_PF_RGBX 2L
#undef org_libjpegturbo_turbojpeg_TJ_PF_BGRX
#define org_libjpegturbo_turbojpeg_TJ_PF_BGRX 3L
#undef org_libjpegturbo_turbojpeg_TJ_PF_XBGR
#define org_libjpegturbo_turbojpeg_TJ_PF_XBGR 4L
#undef org_libjpegturbo_turbojpeg_TJ_PF_XRGB
#define org_libjpegturbo_turbojpeg_TJ_PF_XRGB 5L
#undef org_libjpegturbo_turbojpeg_TJ_PF_GRAY
#define org_libjpegturbo_turbojpeg_TJ_PF_GRAY 6L
#undef org_libjpegturbo_turbojpeg_TJ_BOTTOMUP
#define org_libjpegturbo_turbojpeg_TJ_BOTTOMUP 2L
#undef org_libjpegturbo_turbojpeg_TJ_FORCEMMX
#define org_libjpegturbo_turbojpeg_TJ_FORCEMMX 8L
#undef org_libjpegturbo_turbojpeg_TJ_FORCESSE
#define org_libjpegturbo_turbojpeg_TJ_FORCESSE 16L
#undef org_libjpegturbo_turbojpeg_TJ_FORCESSE2
#define org_libjpegturbo_turbojpeg_TJ_FORCESSE2 32L
#undef org_libjpegturbo_turbojpeg_TJ_FORCESSE3
#define org_libjpegturbo_turbojpeg_TJ_FORCESSE3 128L
#undef org_libjpegturbo_turbojpeg_TJ_FASTUPSAMPLE
#define org_libjpegturbo_turbojpeg_TJ_FASTUPSAMPLE 256L
/*
 * Class:     org_libjpegturbo_turbojpeg_TJ
 * Method:    bufSize
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_libjpegturbo_turbojpeg_TJ_bufSize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_libjpegturbo_turbojpeg_TJ
 * Method:    bufSizeYUV
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_libjpegturbo_turbojpeg_TJ_bufSizeYUV
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_libjpegturbo_turbojpeg_TJ
 * Method:    getScalingFactors
 * Signature: ()[Lorg/libjpegturbo/turbojpeg/TJ/ScalingFactor;
 */
JNIEXPORT jobjectArray JNICALL Java_org_libjpegturbo_turbojpeg_TJ_getScalingFactors
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
