/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TJ */

#ifndef _Included_TJ
#define _Included_TJ
#ifdef __cplusplus
extern "C" {
#endif
#undef TJ_SAMP444
#define TJ_SAMP444 0L
#undef TJ_SAMP422
#define TJ_SAMP422 1L
#undef TJ_SAMP420
#define TJ_SAMP420 2L
#undef TJ_GRAYSCALE
#define TJ_GRAYSCALE 3L
#undef TJ_BGR
#define TJ_BGR 1L
#undef TJ_BOTTOMUP
#define TJ_BOTTOMUP 2L
#undef TJ_FORCEMMX
#define TJ_FORCEMMX 8L
#undef TJ_FORCESSE
#define TJ_FORCESSE 16L
#undef TJ_FORCESSE2
#define TJ_FORCESSE2 32L
#undef TJ_ALPHAFIRST
#define TJ_ALPHAFIRST 64L
#undef TJ_FORCESSE3
#define TJ_FORCESSE3 128L
#undef TJ_FASTUPSAMPLE
#define TJ_FASTUPSAMPLE 256L
#undef TJ_YUV
#define TJ_YUV 512L
/*
 * Class:     TJ
 * Method:    BUFSIZE
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_TJ_BUFSIZE
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
