/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tjCompressor */

#ifndef _Included_tjCompressor
#define _Included_tjCompressor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tjCompressor
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tjCompressor_Init
  (JNIEnv *, jobject);

/*
 * Class:     tjCompressor
 * Method:    Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tjCompressor_Destroy
  (JNIEnv *, jobject);

/*
 * Class:     tjCompressor
 * Method:    Compress
 * Signature: ([BIIII[BIII)J
 */
JNIEXPORT jlong JNICALL Java_tjCompressor_Compress
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
