/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TJDecompressor */

#ifndef _Included_TJDecompressor
#define _Included_TJDecompressor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TJDecompressor
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TJDecompressor_init
  (JNIEnv *, jobject);

/*
 * Class:     TJDecompressor
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TJDecompressor_destroy
  (JNIEnv *, jobject);

/*
 * Class:     TJDecompressor
 * Method:    decompressHeader
 * Signature: ([BJ)LTJHeaderInfo;
 */
JNIEXPORT jobject JNICALL Java_TJDecompressor_decompressHeader
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     TJDecompressor
 * Method:    decompress
 * Signature: ([BJ[BIIIII)V
 */
JNIEXPORT void JNICALL Java_TJDecompressor_decompress
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
