/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tjDecompressor */

#ifndef _Included_tjDecompressor
#define _Included_tjDecompressor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tjDecompressor
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tjDecompressor_Init
  (JNIEnv *, jobject);

/*
 * Class:     tjDecompressor
 * Method:    Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tjDecompressor_Destroy
  (JNIEnv *, jobject);

/*
 * Class:     tjDecompressor
 * Method:    DecompressHeader
 * Signature: ([BJ)LtjHeaderInfo;
 */
JNIEXPORT jobject JNICALL Java_tjDecompressor_DecompressHeader
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     tjDecompressor
 * Method:    Decompress
 * Signature: ([BJ[BIIIII)V
 */
JNIEXPORT void JNICALL Java_tjDecompressor_Decompress
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
