#!/bin/sh

set -u

TMPDIR=

doexit()
{
	if [ ! "$TMPDIR" = "" ]; then
		sudo rm -rf $TMPDIR
	fi
	exit $1
}

usage()
{
	echo "$0 <package name> <version> <build> <RPM architecture> <source dir.>"
	exit 1
}

if [ "$1" = "" ]; then usage $0; fi
PACKAGE_NAME=$1
if [ "$2" = "" ]; then usage $0; fi
VERSION=$2
if [ "$3" = "" ]; then usage $0; fi
BUILD=$3
if [ "$4" = "" ]; then usage $0; fi
SRCDIR=$4

TARBALL=$PACKAGE_NAME-$VERSION.tar.gz
if [ ! -f ./$TARBALL ]; then
	echo ./$TARBALL does not exist.  Run make dist first.
	exit -1
fi

TMPDIR=`mktemp -d /tmp/$PACKAGE_NAME-build.XXXXXX || doexit -1`
mkdir -p $TMPDIR/RPMS || doexit -1
mkdir -p $TMPDIR/SRPMS || doexit -1
mkdir -p $TMPDIR/BUILD || doexit -1
mkdir -p $TMPDIR/SOURCES || doexit -1
mkdir -p $TMPDIR/SPECS || doexit -1
rm -f $PACKAGE_NAME.src.rpm
cp $TARBALL $TMPDIR/SOURCES
cat $SRCDIR/release/libjpeg-turbo.spec | sed s/%{_name}/$PACKAGE_NAME/g \
	| sed s/%{_version}/$VERSION/g | sed s/%{_build}/$BUILD/g \
	| sed s/%{_blddir}/%{_tmppath}/g | sed s@%{_srcdir}/@@g \
	| sed s/#--\>//g >$TMPDIR/SPECS/libjpeg-turbo.spec || doexit -1
rpmbuild -bs --define "_topdir $TMPDIR" $TMPDIR/SPECS/libjpeg-turbo.spec || doexit -1
cp $TMPDIR/SRPMS/$PACKAGE_NAME-$VERSION-$BUILD.src.rpm $PACKAGE_NAME.src.rpm

doexit 0
