#!/bin/sh

set -u
set -e
trap onexit INT
trap onexit TERM
trap onexit EXIT

TMPDIR=

onexit()
{
	if [ ! "$TMPDIR" = "" ]; then
		sudo rm -rf $TMPDIR
	fi
}

usage()
{
	echo "$0 <package name> <version> <build> <RPM architecture> <source dir.>"
	exit 1
}

if [ $# -lt 4 ]; then usage $0; fi
PACKAGE_NAME=$1
VERSION=$2
BUILD=$3
SRCDIR=$4

TARBALL=$PACKAGE_NAME-$VERSION.tar.gz
if [ ! -f ./$TARBALL ]; then
	echo ./$TARBALL does not exist.  Run make dist-gzip first.
	exit -1
fi

TMPDIR=`mktemp -d /tmp/$PACKAGE_NAME-build.XXXXXX`
mkdir -p $TMPDIR/RPMS
mkdir -p $TMPDIR/SRPMS
mkdir -p $TMPDIR/BUILD
mkdir -p $TMPDIR/SOURCES
mkdir -p $TMPDIR/SPECS
rm -f $PACKAGE_NAME.src.rpm
cp $TARBALL $TMPDIR/SOURCES
cat $SRCDIR/release/libjpeg-turbo.spec | sed s/%{_name}/$PACKAGE_NAME/g \
	| sed s/%{_version}/$VERSION/g | sed s/%{_build}/$BUILD/g \
	| sed s/%{_blddir}/%{_tmppath}/g | sed s@%{_srcdir}/@@g \
	| sed s/#--\>//g >$TMPDIR/SPECS/libjpeg-turbo.spec
rpmbuild -bs --define "_topdir $TMPDIR" $TMPDIR/SPECS/libjpeg-turbo.spec
cp $TMPDIR/SRPMS/$PACKAGE_NAME-$VERSION-$BUILD.src.rpm $PACKAGE_NAME.src.rpm

exit
